React hw4
alexanderpono/ponomarenko-alex-otus pull request #26
Opened 2021-11-16 23:19 UTC by alexanderpono

# Домашнее задание 4. Components lifecycle

## Цель:

Написать "сложный" компонент с логикой с рядом дочерних презентационных компонентов, использующих методы жизненного цикла 

1. Написать "сложный" компонент с логикой с рядом дочерних презентационных компонентов(можно как основу взять дз из урока про JSX)

2. Описать constructor как минимум в одном компоненте, объявить в конструкторе стейт и привязать контекст методов

3. Описать componentDidMount как минимум в одном компоненте, получить в нем данные сервера(можно использовать заглушку или сторонние сервисы, например https://jsonplaceholder.typicode.com/). Описать подписку на событие

4. Описать shouldComponentUpdate как минимум в одном компоненте, произвести в нем оптимизацию производительности(если будет притянутый за уши случай - ничего страшного)

5. Описать componentDidUpdate как минимум в одном компоненте, описать в нем условие реализовать обновление стейта при этом условии
    
6. Описать componentWillUnmout в компоненте, где в рамках componentDidMount была подписка на событие, реализовать отписку от этого события

7. Описать все остальные методы с каким-либо функционалом

8. Написать компонент с отловом ошибок, обернуть в него любой компонент

## Критерии оценки:

ДЗ считается принятым, если выполнены первые 6 пунктов, написаны тесты и storybook

## Выполнение д/з №4
1. Создан "сложный" компонент AppStateController, который: 
- реализует управление состоянием приложения
- включает в себя презентационные компоненты AppStateView, FieldSize, GameField

2. Компонент AppStateController реализован как классовый компонент. В AppStateController создан метод constructor(), в котором объявлен state и привязан конекст метода .invert()

3. В компонент AppStateController добавлен метод componentDidMount(). Этот метод делает запрос к удаленному серверу, получает json-данные и заносит их в состояние компонента. Также в методе componentDidMount() устанавливается подписка на событие onmousemove. Добавлен обработчик события .onMouseMove(), который заносит координаты мыши в state. Компонент AppStateView отображает данные с бэка и кооринаты мыши в UI приложения.

4. Для оптимизации производительности - в компонент GameField добавлен метод shouldComponentUpdate(), который возвращает true, если обновлялся размер игрового поля или менялось состояние како-нибудь ячейки.

5. В компонент AppStateController добавлен метод componentDidUpdate(), в котором при опеределенном условии обновляется state компонента AppStateController

6. Создан метод AppStateController.componentWillUnmout(), в котором реализована отписка от события mousemove, а также - отмена промиса запроса к удаленному серверу

7. Дополнены тесты и сторибук.
Покрытие тестами на данный момент:
```
-----------------------------------|---------|----------|---------|---------|-------------------
File                               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------------|---------|----------|---------|---------|-------------------
All files                          |   97.27 |       75 |   97.37 |   96.97 |                   
 src                               |     100 |      100 |     100 |     100 |                   
  consts.ts                        |     100 |      100 |     100 |     100 |                   
 src/components/AppStateController |   95.65 |    58.33 |   96.15 |      95 |                   
  AppStateController.tsx           |   92.68 |     37.5 |      95 |   91.89 | 26,92,116         
  appReducer.ts                    |     100 |      100 |     100 |     100 |                   
 src/components/AppStateView       |     100 |      100 |     100 |     100 |                   
  AppStateView.tsx                 |     100 |      100 |     100 |     100 |                   
 src/components/Cell               |     100 |      100 |     100 |     100 |                   
  Cell.tsx                         |     100 |      100 |     100 |     100 |                   
 src/components/FieldSize          |     100 |      100 |     100 |     100 |                   
  FieldSize.tsx                    |     100 |      100 |     100 |     100 |                   
 src/components/GameField          |     100 |      100 |     100 |     100 |                   
  GameField.tsx                    |     100 |      100 |     100 |     100 |                   
 src/testFramework/lib             |     100 |      100 |     100 |     100 |                   
  reducer.ts                       |     100 |      100 |     100 |     100 |                   
-----------------------------------|---------|----------|---------|---------|-------------------

Test Suites: 7 passed, 7 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        4.825 s
Ran all test suites.
```

Текущая версия сторибук в chromatic:
https://6168a14038f17a003a388098-fbripsbzsk.chromatic.com/?path=/story/appstatecontroller--game

Тесты в chromatic:
https://www.chromatic.com/build?appId=6168a14038f17a003a388098&number=5

2021-11-19 06:12 UTC, vasiliev-alexey requested changes

2021-11-19 06:12 UTC, vasiliev-alexey commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +export class AppStateController extends React.Component<{}, AppState> {
Насчет нейминга не очень понял. Если это попытка сделать MVC -   то в данном случае Контроллер заниматеся отрисовкой - что не является его ролью. Если  это  хранитель состояния - то наверно правильнее ожидался неминг Manager

2021-11-19 06:12 UTC, vasiliev-alexey commented on react-2021-09/react-2021-09-hw04/src/components/AppStateView/AppStateView.tsx
> +                <span className="value">{props.appState.fieldWidth}</span>
Идеальная картина потренироватья над деструктуризацией пропсов

2021-11-19 23:05 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +            <div>
исправил в следующем коммите "fixes after code review"

2021-11-19 23:06 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +                    widthPixels={this.state.fieldWidth * CELL_WIDTH}
спасибо, я пока использовал CSS Reset в следующем коммите "fixes after code review". А в каком браузере и на какой ОС ты обнаружил искажение верстки?

2021-11-19 23:07 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +type CancelablePromise = { promise: Promise<any>; cancel: () => void };
ок, принял. В следующем коммите убрал этот код, заменил на AbortController

2021-11-19 23:08 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +const makeCancelable = (promise: Promise<any>): CancelablePromise => {
спасибо, классная идея! Использую AbortController в следующем коммите "fixes after code review"

2021-11-19 23:09 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/appReducer.ts
> +export const DEFAULT_CELL_STATE = CELL_LIVE;
соберу в следующей домашке - в т.ч. добавлю алиасы, чтобы убрать "../../" в импортах

2021-11-19 23:09 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/appReducer.ts
> +type DataFromBack = Record<string, any>;
спасибо, принял. Исправил в следующем коммите "fixes after code review"

2021-11-19 23:10 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +export class AppStateController extends React.Component<{}, AppState> {
ок, переименовал. Исправил в следующем коммите "fixes after code review"

2021-11-19 23:10 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateView/AppStateView.tsx
> +                <span className="value">{props.appState.fieldWidth}</span>
ок, добавил деструктуризацию в интерфейсе функции. Исправил в следующем коммите "fixes after code review"

2021-11-19 23:10 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/appReducer.ts
> +                fieldHeight: Number(action.payload.fieldHeight),
спасибо, исправил

2021-11-20 07:31 UTC, vasiliev-alexey commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +                    widthPixels={this.state.fieldWidth * CELL_WIDTH}
![изображение](https://user-images.githubusercontent.com/3257253/142718450-2d074cfb-681b-4464-adef-e1a0ec2f701d.png)

ububtu 20.04  Firefox 94.0
Экран 2560*1080

2021-11-21 11:10 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/src/components/AppStateController/AppStateController.tsx
> +                    widthPixels={this.state.fieldWidth * CELL_WIDTH}
хм, мне пока не удалось воспроизвести эту проблему с версткой на VirtualBox / ubuntu 20 / FireFox 94.0.
build 7 - storybook - https://6168a14038f17a003a388098-qfauqmhgsd.chromatic.com/?path=/story/appstatemanager--game
build 6 - storybook - https://6168a14038f17a003a388098-hagxlrmspt.chromatic.com/?path=/story/appstatemanager--game
build 5 - storybook - https://6168a14038f17a003a388098-fbripsbzsk.chromatic.com/?path=/story/appstatecontroller--game

2021-11-22 06:26 UTC, K0SM0S1989 approved these changes

2021-11-22 17:16 UTC, artem-volirvag commented on react-2021-09/react-2021-09-hw04/package.json
> +    "enzyme": "^3.11.0",
вы используете enzyme?

2021-11-22 19:04 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/package.json
> +    "enzyme": "^3.11.0",
да, есть enzyme в паре тестов

2021-11-22 19:06 UTC, alexanderpono commented on react-2021-09/react-2021-09-hw04/package.json
> +    "webpack": "^4.42.1",
да, я использовал 4-й, т.к. storybook по умолчанию использует конфигурацию 4-го webpack-а, из-за чего сам сторибук не стартует на 5 webpack-е без волшебных пинков. Пошел по пути понижения версии webpack.

2021-11-23 19:56 UTC, alexanderpono commented
пересоберу ветку hw4 заново - без копирования исходников в новую папку

2021-11-23 19:56 UTC, closed without merging